baseurl         = ""
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Alfie Qashwa"
  subtitle    = "Cogito • Ergo • Sum • Sentio • Ergo • Sum"
  copyright   = "© 2018"
  favicon     = "img/radiohead-logo.png"

  cover       = "img/radiohead.jpg"
  description = "Sentio Ergo Sum."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "alfieqashwa"
  githubName = "alfieqashwa"
  #fbName = "fakeghost"
  #linkedinName = "eueung"
  mediumName = ""

  logo = ""
  orgName = "Alfie Qashwa"
  orgWebsite = "https://www.alfieqashwa.me"
  orgDescription = "Cogito Ergo Sum - Sentio Ergo Sum"

  showSupport = true

  author = "Alfie Qashwa"
  authorAvatar = "img/radiohead-logo.png"
  authorLocation = "Ciputat, ID"
  authorWebsite = "https://alfieqashwa.github.io"
  authorDescription = "Ikatlah Ilmu dengan Menuliskannya"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Programming"
  url = "/tags/programming/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "Project & Interest"
  url = "https://www.alfieqashwa.me/"
  weight = 95

